### ISSUE TITLE
[Notebooks] Notebooks aren't in sync with latest NAT version

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/nat#7]
**Unexpected behaviour:**

The notebooks aren't in sync with the API of the latest version of NAT (0.4+).

The goal is to make the notebooks compatible with the API of NAT 0.4+.

Wait the resolution of #6.

**Comment by christian-oreilly** [comment]
Should be closed now. @pafonta, I leave the honor to you.

**Comment by pafonta** [comment]
Hum... Yes. It didn't have done it because GitHub needs the keyword for each referenced issue after all...
